sed -i "" "s/C1 /C1P/" test.prm
sed -i "" "s/C2 /C2P/" test.prm
sed -i "" "s/CC3 /CC3P/" test.prm
sed -i "" "s/C4 /C4P/" test.prm
sed -i "" "s/C5 /C5P/" test.prm
sed -i "" "s/C6 /C6P/" test.prm
sed -i "" "s/C7 /C7P/" test.prm
sed -i "" "s/C8 /C8P/" test.prm
sed -i "" "s/C9 /C9P/" test.prm
sed -i "" "s/C10 /C10P/" test.prm
sed -i "" "s/C11 /C11P/" test.prm
sed -i "" "s/C12 /C12P/" test.prm
sed -i "" "s/C13 /C13P/" test.prm
sed -i "" "s/C14 /C14P/" test.prm
sed -i "" "s/C15 /C15P/" test.prm
sed -i "" "s/C16 /C16P/" test.prm
sed -i "" "s/C17 /C17P/" test.prm
sed -i "" "s/C18 /C18P/" test.prm
sed -i "" "s/C19 /C19P/" test.prm
sed -i "" "s/C20 /C20P/" test.prm
sed -i "" "s/C1A /C1AP/" test.prm
sed -i "" "s/C2A /C2AP/" test.prm
sed -i "" "s/C3A /C3AP/" test.prm
sed -i "" "s/C4A /C4AP/" test.prm
sed -i "" "s/C1B /C1BP/" test.prm
sed -i "" "s/C2B /C2BP/" test.prm
sed -i "" "s/C3B /C3BP/" test.prm
sed -i "" "s/C4B /C4BP/" test.prm
sed -i "" "s/C1C /C1CP/" test.prm
sed -i "" "s/C2C /C2CP/" test.prm
sed -i "" "s/C3C /C3CP/" test.prm
sed -i "" "s/C4C /C4CP/" test.prm
sed -i "" "s/C1D /C1DP/" test.prm
sed -i "" "s/C2D /C2DP/" test.prm
sed -i "" "s/C3D /C3DP/" test.prm
sed -i "" "s/C4D /C4DP/" test.prm
sed -i "" "s/CAA /CAAP/" test.prm
sed -i "" "s/CAB /CABP/" test.prm
sed -i "" "s/CAC /CACP/" test.prm
sed -i "" "s/CAX /CAXP/" test.prm
sed -i "" "s/CBA /CBAP/" test.prm
sed -i "" "s/CBB /CBBP/" test.prm
sed -i "" "s/CBC /CBCP/" test.prm
sed -i "" "s/CBY /CBYP/" test.prm
sed -i "" "s/CED /CEDP/" test.prm
sed -i "" "s/CGA /CGAP/" test.prm
sed -i "" "s/CGD /CGDP/" test.prm
sed -i "" "s/CHA /CHAP/" test.prm
sed -i "" "s/CHB /CHBP/" test.prm
sed -i "" "s/CHC /CHCP/" test.prm
sed -i "" "s/CHD /CHDP/" test.prm
sed -i "" "s/CMA /CMAQ/" test.prm
sed -i "" "s/CMB /CMBP/" test.prm
sed -i "" "s/CMC /CMCP/" test.prm
sed -i "" "s/CMD /CMDP/" test.prm
sed -i "" "s/HAC /HACP/" test.prm
sed -i "" "s/HCC /HCCP/" test.prm
sed -i "" "s/MGC /MGCP/" test.prm
sed -i "" "s/N_A /N_AP/" test.prm
sed -i "" "s/N_B /N_BP/" test.prm
sed -i "" "s/N_C /N_CP/" test.prm
sed -i "" "s/N_D /N_DP/" test.prm
sed -i "" "s/O1A /O1AP/" test.prm
sed -i "" "s/O2A /O2AP/" test.prm
sed -i "" "s/O1D /O1DP/" test.prm
sed -i "" "s/O2D /O2DP/" test.prm
sed -i "" "s/OBB /OBBP/" test.prm
sed -i "" "s/OBD /OBDP/" test.prm
